move values from array to .sh scripts

diff --git a/bin/lb_get_values b/bin/lb_get_values
--- a/bin/lb_get_values
+++ b/bin/lb_get_values
@@ -10,20 +10,22 @@ echo "$LB_GET_VALUES" | while read _VALUE_STRING; do
         read _VALUE_NAME _VALUE_TEST
         echo "echo -n '$LB_RUNDATE-logbuster values $_VALUE_NAME'"
 
-        [ -v "lb_values[$_VALUE_NAME]" ] && {
-            echo "_value_result=\$(lb_test_result ${lb_values[$_VALUE_NAME]})"
-            echo "if [ \"\$_value_result\" == _lb_error ]; then"
-            echo "echo ' error'; else"
-            [ -z "$_VALUE_TEST" ] && {
-                echo "echo ' ok'"
-            } || {
-                echo "if [ \"\$_value_result\" $_VALUE_TEST ]; then echo ' ok'; else echo ' warn'; fi"
-            }
-            echo "echo \"\$_value_result\"; fi"
+        echo "_value_result=\$(bash <<'EOF'"
+        echo "exec 2>/dev/null"
+
+        cat helpers/values_sh/$_VALUE_NAME.sh
+
+        echo "[ \$? -eq 0 ] || echo -n _lb_error"
+        echo "EOF"
+        echo ")"
+        echo "if [ \"\$_value_result\" == _lb_error ]; then echo ' error'"
+        echo "else"
+
+        [ -z "$_VALUE_TEST" ] && {
+            echo "echo ' ok'"
         } || {
-            echo "_value_result=\$(lb_test_result $_VALUE_TEST)"
-            echo "if [ \"\$_value_result\" == _lb_error ]; then"
-            echo "echo ' warn_custom'; else echo ' ok'; echo \"\$_value_result\"; fi"
+            echo "if [ \"\$_value_result\" $_VALUE_TEST ]; then echo ' ok'; else echo ' warn'; fi"
         }
+        echo "echo \"\$_value_result\"; fi"
     }
 done
